const api=window.RECON_API_BASE;
const sources={order:['Orders','JSON','.json','id, reference, amount, currency, created_at, merchant'],settlement:['Settlements','CSV','.csv','id, reference, amount, currency, settled_at, merchant'],bank:['Bank credits','XML','.xml','id, reference, amount, currency, credited_at, counterparty']};
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
async function request(path,opts={}){const r=await fetch(api+path,opts);if(!r.ok){const body=await r.json().catch(()=>({detail:r.statusText}));throw Error(body.detail)}return r.json()}
function msg(text,bad=false){const e=document.querySelector('#message');if(e){e.textContent=text;e.className='mt-4 '+(bad?'text-rose-700':'text-cyan-800')}}

async function startWorkspace(){try{let id=sessionStorage.reconBatch;if(!id){id=(await request('/batches',{method:'POST'})).batch_id;sessionStorage.reconBatch=id}renderUploads(await request('/batches/'+id))}catch(e){msg('We could not prepare your review workspace: '+e.message,true)}}
function renderUploads(batch){const files=Object.fromEntries(batch.files.map(x=>[x.source,x]));document.querySelector('#upload-panel').innerHTML=Object.entries(sources).map(([source,[label,format,accept,needs]])=>{const file=files[source];return `<article class="bg-white border rounded-xl p-5"><p class="text-cyan-700 text-sm font-semibold">${format} FILE</p><h3 class="font-bold text-lg">${label}</h3><p class="text-xs text-slate-500 h-10 mt-2">Required: ${needs}</p><input id="file-${source}" type="file" accept="${accept}" class="mt-3 text-sm w-full" onchange="uploadFile('${source}')"><p class="mt-3 text-sm ${file?'text-emerald-700':'text-slate-500'}">${file?`✓ ${esc(file.filename)} · ${file.accepted_rows} accepted${file.failed_rows?` · ${file.failed_rows} need attention`:''}`:'Not uploaded yet'}</p></article>`}).join('');const ready=Object.keys(sources).every(s=>files[s]);const b=document.querySelector('#run-button');b.disabled=!ready;b.className='rounded-lg px-5 py-3 font-bold '+(ready?'bg-cyan-700 text-white':'bg-slate-200 text-slate-500');document.querySelector('#readiness').textContent=ready?'All three files are ready. Start when you are ready.':'Upload all three files to continue.';if(batch.parse_failures.length)msg(`${batch.parse_failures.length} row(s) need attention. You can inspect them after processing.`)}
async function uploadFile(source){const file=document.querySelector('#file-'+source).files[0];if(!file)return;msg(`Checking and loading ${file.name}…`);try{const form=new FormData();form.append('file',file);renderUploads(await request(`/batches/${sessionStorage.reconBatch}/files/${source}`,{method:'POST',body:form}));msg(`${sources[source][0]} loaded successfully.`)}catch(e){msg('We could not load this file: '+e.message,true)}}
async function startClientReview(){const b=document.querySelector('#run-button');b.disabled=true;await runReview('/reconcile/jobs?batch_id='+encodeURIComponent(sessionStorage.reconBatch),b)}
async function runBuildathonDemo(){await runReview('/demo/jobs')}
let progressStartedAt=0,progressStatus={},progressHistory=[],progressClock;
function progressTime(){const elapsed=Math.floor((Date.now()-progressStartedAt)/1000),wait=Math.max(0,Math.ceil((Number(progressStatus.wait_until||0)*1000-Date.now())/1000)),format=s=>`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;return wait?`${format(wait)} until Gemini retry · ${format(elapsed)} elapsed`:`${format(elapsed)} elapsed`}
function renderProgress(status){const panel=document.querySelector('#processing-panel');if(!panel)return;const key=`${status.stage||''}|${status.detail||''}`;if(!progressHistory.length||progressHistory.at(-1).key!==key)progressHistory.push({key,stage:status.stage||'Processing',detail:status.detail||''});progressStatus=status;panel.classList.remove('hidden');document.querySelector('#progress-stage').textContent=status.stage||'Processing';document.querySelector('#progress-detail').textContent=status.detail||'';document.querySelector('#progress-count').textContent=status.current&&status.total?`Progress: ${status.current} of ${status.total}`:'Progress details update as each task completes.';document.querySelector('#progress-history').innerHTML=progressHistory.map((event,index)=>`<li class="${index===progressHistory.length-1?'text-cyan-300':'text-slate-400'}">${index===progressHistory.length-1?'●':'✓'} ${esc(event.stage)}${event.detail ? `: ${esc(event.detail)}` : ''}</li>`).join('');const timer=document.querySelector('#progress-timer');if(timer)timer.textContent=progressTime()}
async function runReview(endpoint,button){progressStartedAt=Date.now();progressStatus={stage:'Starting reconciliation',detail:'Creating a background job so this page stays responsive.'};progressHistory=[];renderProgress(progressStatus);progressClock=setInterval(()=>renderProgress(progressStatus),250);try{const job=await request(endpoint,{method:'POST'});let status;do{await new Promise(resolve=>setTimeout(resolve,1200));status=await request('/reconcile/jobs/'+job.job_id);renderProgress(status)}while(status.status==='queued'||status.status==='processing');if(status.status==='failed')throw Error(status.message||'The reconciliation job could not complete.');clearInterval(progressClock);sessionStorage.reconRun=JSON.stringify(status.result);location.href='results.html'}catch(e){clearInterval(progressClock);msg('We could not complete the review: '+e.message,true);if(button)button.disabled=false}}

let currentExceptions=[];
const toolLabels={lookup_record:'checked the order record',search_related_transactions:'searched for related transactions',check_timing_window:'checked the timing',compare_amounts:'compared the amounts'};
const ruleLabels={missing_settlement:'no settlement record was found for this order',missing_bank_credit:'no bank credit was found for this order',amount_comparison_failed:'the recorded amounts do not agree',settlement_window_exceeded:'the bank credit arrived outside the expected timing window',duplicate_bank_reference:'more than one bank credit used the same reference',unmatched_bank_record:'the bank credit could not be linked to an order'};
const exceptionLabels={MISSING_SETTLEMENT:'Missing Settlement',MISSING_BANK_CREDIT:'Missing Bank Credit',AMOUNT_MISMATCH:'Amount Mismatch',TIMING_ANOMALY:'Timing Anomaly',DUPLICATE_TRANSACTION:'Duplicate Transaction',ORPHAN_RECORD:'Orphan Record'};
function explanationFor(x){const a=x.agent||{};return a.explanation||a.reason_if_abstained||'Manual review is required.'}
function flaggedBecause(x){return ruleLabels[x.rule_applied]||String(x.exception_type||'record issue').replaceAll('_',' ').toLowerCase()}
function investigatedUsing(x){const tools=[...new Set((x.agent?.tool_trace||[]).map(step=>toolLabels[step.tool]).filter(Boolean))];return tools.length?tools.join(', '):'no automated record checks were completed'}
function statusLabel(x){return x.agent?.outcome==='RESOLVED'?'Matched — explained.':'Needs your review.'}
function statusBadge(x){return `<span class="status-badge ${x.agent?.outcome==='RESOLVED'?'status-resolved':'status-review'}">${statusLabel(x)}</span>`}
function auditSequence(x){return `${x.order_id||x.matched_txn_ids[0]||'Record'}: Order ingested → Flagged as exception → Investigated → ${x.agent?.outcome==='RESOLVED'?'Resolved':'Needs review'}`}
async function renderClientResults(){const run=JSON.parse(sessionStorage.reconRun||'null');if(!run)return location.href='index.html';const m=run.evaluation;document.querySelector('#summary').textContent=`${m.matched_records} of ${m.total_records} orders were matched automatically. Review any exceptions before closing this case.`;document.querySelector('#workflow').innerHTML=(run.workflow||[]).map(x=>`<span class="bg-emerald-100 text-emerald-800 px-3 py-1 rounded-full text-sm">✓ ${esc(x)}</span>`).join('');const value=x=>x==null?'Not estimated':x+'%';const cards=[['Automatic match rate',m.match_rate+'%'],['Orders reviewed',m.total_records],['Items needing review',run.results.filter(x=>x.status==='EXCEPTION').length],['Resolution accuracy',value(m.resolution_accuracy)],['Honesty score',value(m.honesty_score)]];document.querySelector('#metrics').innerHTML=cards.map(([k,v])=>`<article class="bg-white border rounded-xl p-5"><p class="text-slate-500 text-sm">${k}</p><p class="text-3xl font-bold mt-2">${v}</p></article>`).join('');const exceptions=currentExceptions=run.results.filter(x=>x.status==='EXCEPTION');const groups=Object.keys(exceptionLabels).map(type=>[type,exceptions.filter(x=>x.exception_type===type)]).filter(([,items])=>items.length);document.querySelector('#exceptions').innerHTML=groups.length?groups.map(([type,items])=>exceptionGroup(type,items)).join(''):'<div class="bg-emerald-50 text-emerald-900 border border-emerald-200 rounded-xl p-5">No exceptions were found.</div>';document.querySelector('#audit-sequence').innerHTML=exceptions.map(x=>`<p>${esc(auditSequence(x))}</p>`).join('');if(!run.batch_id){document.querySelector('#uploaded-data').innerHTML='<p class="text-slate-600">This was the fixed-seed synthetic demonstration. The hidden answer key was available only to evaluation.</p>';return}try{const batch=await request('/batches/'+run.batch_id);document.querySelector('#uploaded-data').innerHTML=`<p class="mb-3 text-sm text-slate-600">${batch.records.length} accepted records · ${batch.parse_failures.length} validation issue(s)</p><pre class="p-3 rounded bg-slate-950 text-slate-100 text-xs overflow-auto">${esc(JSON.stringify({accepted_records:batch.records,rows_needing_attention:batch.parse_failures},null,2))}</pre>`}catch(e){document.querySelector('#uploaded-data').textContent=e.message}}
function exceptionGroup(type,items){const resolved=items.filter(x=>x.agent?.outcome==='RESOLVED').length,review=items.length-resolved;return `<section class="exception-group"><header><b>${exceptionLabels[type]}</b><span>${items.length} record${items.length===1?'':'s'}, ${resolved} explained, ${review} need${review===1?'s':''} your review</span></header><div class="space-y-3 mt-3">${items.map(x=>exceptionCard(x)).join('')}</div></section>`}
function evidenceRows(x){
 const rows=[['Reference',x.evidence?.reference||'Not provided'],['Record ID',x.order_id||x.matched_txn_ids?.join(', ')||'Not provided']];
 for(const step of (x.agent?.tool_trace||[])){
  const result=step.result||{};
  if(step.tool==='compare_amounts')rows.push(['Amount comparison',result.equal?'Amounts match':result.difference!=null?`Difference: ${result.difference}`:'Could not compare amounts']);
  if(step.tool==='check_timing_window')rows.push(['Timing checked',result.days!=null?`${result.days} day(s) apart${result.within_t_plus_2?' (within expected window)':' (outside expected window)'}`:'Dates were unavailable']);
  if(step.tool==='lookup_record'&&result?.amount!=null)rows.push(['Record amount',`${result.amount} ${result.currency||''}`.trim()]);
 }
 return [...new Map(rows.map(row=>[row[0],row])).values()];
}
function exceptionCard(x){return `<article class="bg-white border rounded-xl p-5"><div class="flex flex-col md:flex-row md:items-center md:justify-between gap-2"><div><b>Record ${esc(x.order_id||x.matched_txn_ids?.[0]||'not provided')}</b><small class="block text-slate-500">Reference: ${esc(x.evidence?.reference||'Not provided')}</small></div>${statusBadge(x)}</div><div class="plain-language mt-4"><p><b>Flagged because:</b> ${esc(flaggedBecause(x))}</p><p><b>Investigated using:</b> ${esc(investigatedUsing(x))}</p><p><b>Concluded:</b> ${esc(explanationFor(x))}</p></div><details class="mt-3"><summary class="cursor-pointer text-cyan-800">Show calculation and evidence</summary><table class="evidence-table mt-2"><tbody>${evidenceRows(x).map(([label,value])=>`<tr><th>${esc(label)}</th><td>${esc(value)}</td></tr>`).join('')}</tbody></table></details></article>`}
function exportExceptionsCsv(){const quote=value=>`"${String(value??'').replaceAll('"','""')}"`;const rows=[['reference','exception type','status','explanation or reason'],...currentExceptions.map(x=>[x.evidence?.reference||'',String(x.exception_type||'').replaceAll('_',' '),statusLabel(x),explanationFor(x)])];const blob=new Blob([rows.map(row=>row.map(quote).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'});const link=document.createElement('a');link.href=URL.createObjectURL(blob);link.download='reconaudit-exceptions.csv';link.click();URL.revokeObjectURL(link.href)}
async function verifyLedger(){try{const r=await request('/audit/verify'),e=document.querySelector('#ledger-status');e.textContent=r.valid?`✓ Verified: ${r.records_checked} linked records are intact.`:'Verification warning: the audit trail needs review.';e.className=r.valid?'text-sm text-emerald-700':'text-sm text-rose-700'}catch(e){document.querySelector('#ledger-status').textContent=e.message}}
